"""
Configuration settings for Tell-A-Vision server
"""

# ===== CAMERA SETTINGS =====
CAMERA_INDEX = 0

RESOLUTION_ATTEMPTS = [
    (640, 360),
]

CAMERA_WIDTH = 640
CAMERA_HEIGHT = 360
CAMERA_FPS = 30
CAMERA_BUFFER_SIZE = 1

# Camera Lighting/Exposure
CAMERA_BRIGHTNESS = 150
CAMERA_CONTRAST = 140
CAMERA_SATURATION = 140
CAMERA_EXPOSURE = -4 #-5

# ===== ENCODING SETTINGS =====
JPEG_QUALITY = 60
TARGET_FPS = 30

# ===== BALL TRACKING SETTINGS =====
NUM_BALLS = 2
MIN_BALL_RADIUS = 5
MAX_BALL_RADIUS = 100
MIN_BALL_AREA = 50

# ===== SERVER SETTINGS =====
DEFAULT_PORT = 5000
HOST = "127.0.0.1"

# ===== PERFORMANCE SETTINGS =====
FRAME_BUFFER_SIZE = 30