"""
Configuration settings for Tell-A-Vision server
"""

# ===== CAMERA SETTINGS =====
CAMERA_INDEX = 0
CAMERA_WIDTH = 630
CAMERA_HEIGHT = 360
CAMERA_FPS = 30
CAMERA_RESOLUTION_ATTEMPTS = [
    (630, 360),
]
CAMERA_BUFFER_SIZE = 1

CAMERA_BRIGHTNESS = 150
CAMERA_CONTRAST = 140
CAMERA_SATURATION = 140
CAMERA_EXPOSURE = -5

# Legacy alias used by pipeline.py's _resolution_attempts default
RESOLUTION_ATTEMPTS = CAMERA_RESOLUTION_ATTEMPTS

# ===== ENCODING SETTINGS =====
JPEG_QUALITY = 60
TARGET_FPS = 30

# ===== BALL TRACKING SETTINGS =====
NUM_BALLS = 4
MIN_BALL_RADIUS = 5
MAX_BALL_RADIUS = 100
MIN_BALL_AREA = 50

# ===== SERVER SETTINGS =====
DEFAULT_PORT = 5000
HOST = "127.0.0.1"

# ===== PERFORMANCE SETTINGS =====
FRAME_BUFFER_SIZE = 30