"""
Configuration settings for Tell-A-Vision server
Ball tracking only, optimized for low latency
"""

# ===== CAMERA SETTINGS =====
CAMERA_INDEX = 0

# Resolution fallback order (for 60fps support)
RESOLUTION_ATTEMPTS = [
    (424, 240),
    (640, 480),
    (640, 360),
]

CAMERA_WIDTH = 640
CAMERA_HEIGHT = 360
CAMERA_FPS = 30
CAMERA_BUFFER_SIZE = 1

# Camera Lighting/Exposure
CAMERA_BRIGHTNESS = 150
CAMERA_CONTRAST = 140
CAMERA_SATURATION = 140
CAMERA_EXPOSURE = -5

# ===== ENCODING SETTINGS =====
JPEG_QUALITY = 60
TARGET_FPS = 30

# ===== BALL TRACKING SETTINGS =====
NUM_BALLS = 4
MIN_BALL_RADIUS = 5
MAX_BALL_RADIUS = 100
MIN_BALL_AREA = 50

# ===== SERVER SETTINGS =====
DEFAULT_PORT = 5000
HOST = "127.0.0.1"

# ===== PERFORMANCE SETTINGS =====
FRAME_BUFFER_SIZE = 30

# ===== BIGTRACK FOOT MOUSE =====
BIGTRACK_VENDOR_ID = 0x2046
BIGTRACK_PRODUCT_ID = 0x0126
BIGTRACK_SENSITIVITY = 0.005
BIGTRACK_VERTICAL_MULTIPLIER = 3.0
BIGTRACK_NAV_THRESHOLD = 0.3
BIGTRACK_DOUBLE_CLICK_THRESHOLD = 0.5